cloud-gov/external-domain-broker-migrator

- docker/Dockerfile.dev
- migrator/config.py
- migrator/db.py
- migrator/extensions.py
- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- requirements.txt
- tests/unit/test_cdn_db.py
- tests/unit/test_config.py
- add database connection
- update some connection stuff in the docker container
[Note the any security considerations here, or make note of why there are none]
> initial database connection

- ci/pipeline.yml
- add base pipeline 
- pipeline reconfigures itself. fixes #16 
None
> add base pipeline

- ci/pipeline.yml
> add tests in CI

- migrator/models.py
- tests/unit/test_cdn_db.py
- tests/unit/test_config.py
- add models for cdn-broker database. Fixes #1 
None
> add models for cdn-broker database

- migrator/__main__.py
- migrator/db.py
- tests/unit/test_cdn_db.py
- add checks for startups
- create __main__ so the project can actually be called
None
> Startup checks

- ci/pipeline.yml
- manifest.yml
- deploy to dev. Fixes #22 
None
> add dev deployment

- ci/pipeline.yml
- migrator/config.py
- migrator/extensions.py
- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- requirements.txt
- tests/unit/test_config.py
- add aws config
this now means this app has access to AWS
> Aws config

- migrator/migration.py
- tests/conftest.py
- tests/lib/fake_aws.py
- tests/lib/fake_cloudfront.py
- tests/unit/test_migration.py
- parse existing cloudfront config
fixes #5 
None
> parse cloudfront config

- ci/pipeline.yml
- docker/external-domain-broker-schema.sql
- docker/start-servers.sh
- manifest.yml
- migrator/config.py
- migrator/db.py
- migrator/models.py
- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- requirements.txt
- tests/lib/fake_cloudfront.py
- tests/unit/test_cdn_db.py
- tests/unit/test_config.py
- tests/unit/test_migration.py
- add external-domain-broker database connection
fixes #3 
None
> Connect to edbdb

- migrator/db.py
- migrator/migration.py
- tests/unit/test_migration.py
- Add logic to create external-domain-broker instance
- fix db session to map EdbBase models to external_domain_engine
None
> Add logic to create external-domain-broker instance

- migrator/config.py
- tests/unit/test_config.py
- fix hosted zone id env mismatch
None
> fix hosted zone id env mismatch

- README.md
- update README with docs about the plan
None
> update README with docs about the plan

- README.md
> Workflow docs

- ci/pipeline.yml
> add cf deployment vars

- migrator/cf.py
- migrator/extensions.py
- migrator/migration.py
- migrator/service_plan.py
- tests/conftest.py
- tests/lib/fake_cf.py
- tests/unit/test_cf.py
- tests/unit/test_migration.py
- add function to enable service plan in organization
None
> add function to enable service plan in organization

- migrator/config.py
- tests/unit/test_config.py
- remove edb database config
- 
- 
None
> remove edb database config

- README.md
- update plan documentation to match plan changes
None
> update plan documentation to match plan changes

- ci/pipeline.yml
- make cf endpoint variable consistent
None
> make cf endpoint variable consistent

- migrator/dns.py
- tests/lib/dns.py
- tests/unit/test_dns.py
Implements issue #43:
- Add a function to query TXT records
- Add a function to query a domain for TXT records and see if any match the semaphore
- Unit tests for the above
None known; these changes only query DNS records.
> Check for semaphore

- flagger/aws.py
- migrator/cf.py
- migrator/config.py
- migrator/extensions.py
- migrator/migration.py
- tests/lib/fake_route53.py
- tests/unit/test_migration.py
- catch fall-through implicitly
- make retries configurably
- assert the number of retries in tests
- reduce exit points
None
> Enable migrator plan in spaces 2

- migrator/cf.py
- migrator/migration.py
- tests/unit/test_cf.py
- tests/unit/test_migration.py
- purge old instance on completion fixes #81
None
> purge old instance on completion

- migrator/models.py
- add models for ALB instances to migrator
None
> add models for ALB instances to migrator

- migrator/cf.py
- migrator/extensions.py
- migrator/migration.py
- tests/unit/test_migration.py
- add matchers to make assertions about posts
- fix bugs found by these matchers
None
> add more validation in fake_requests_tests

- ci/pipeline.yml
- migrator/config.py
- migrator/migration.py
- migrator/smtp.py
- tests/unit/test_config.py
- fixes #70
This exposes some guids via email, but we've so far considered those non-sensitive.
> add email notification on failures

- migrator/__main__.py
- migrator/smtp.py
- send an email report when done
None
> email report when done migrating

- migrator/dns.py
- tests/unit/test_migration.py
- add CNAME validation for site dns
None
> Dns validation

- migrator/migration.py
- get migration earlier so we can call `has_valid_dns` on it
None
> migration has `has_valid_dns`, not route

- flagger/__main__.py
- import required session_handler
None
> import required session_handler

- flagger/__main__.py
- don't treat lists like functions
- fix function names
None
> Flagger fixes

- flagger/aws.py
- set TTL on TXT record upsert
None
> TXT records need TTL to be set

- tests/lib/fake_route53.py
- match change in tests 
- 
None
> Txt needs ttl

- flagger/aws.py
- tests/unit/test_aws.py
- add quotes to txt value, because apparently that's what route53 wants
None
> route53 wants all the quotes

- manifest.yml
- migrator/__main__.py
- migrator/migration.py
- tests/unit/test_arg_parse.py
- tests/unit/test_migration.py
- allow one-off or continuous running options
None
> Allow running against one specified instance or as daemon

- migrator/migration.py
- tests/unit/test_migration.py
- Catch when `Migration` instances fail to initialize. This currently happens because the instance exists in the broker db but not ccdb (hopefully, this is just a staging thing 🤞 ) One thing to note: if this happens, we're not reporting that instance as skipped, migrated, or failed in the report.
None
> catch instances failing to initialize

- migrator/migration.py
- has_valid_dns is a property, not a function
None
> has_valid_dns is a property, not a function

- migrator/migration.py
- move failure email to base migration
- reference `migration.route.state`, since we don't have the `route` itself
None
> fix failures that happen during failures

- migrator/extensions.py
- migrator/migration.py
- remove the rest of the catalog guid references
- also add repr to domain route so it'll show up better in emails
- 
- 
None
> update remaining references to plan id

- migrator/cf.py
- pass args by keyword explicitly, since apparently I can't be trusted to pass them in the correct order
None
> pass parameters correctly

- migrator/cf.py
- tests/unit/test_cdn_migration.py
- tests/unit/test_cf.py
- tests/unit/test_domain_migration.py
- tests/unit/test_migration.py
- allow async service instance operations
None
> allow async service instance operations

- migrator/cf.py
- migrator/migration.py
- tests/unit/test_cdn_migration.py
- tests/unit/test_cf.py
- tests/unit/test_domain_migration.py
- pass required domains param to service instance create
None
> pass required domains param to service instance create

- ci/pipeline.yml
- migrator/config.py
- migrator/extensions.py
- migrator/migration.py
- tests/unit/test_cdn_migration.py
- tests/unit/test_config.py
- tests/unit/test_domain_migration.py
- use plan ids rather than catalog ids for updates
- also fix some update tests and code for domain updates
None
> Configure plan ids for updates, too

- migrator/config.py
- increase update polling timeout to match broker
None
> increase timeout to match broker

- migrator/extensions.py
- migrator/migration.py
- give a more meaningful name to the migration instance
None
> better name for migrating instance

- migrator/migration.py
- reference `route` correctly
- make error handling a little less likely to blow up
- 
None
> use migration.route

- ci/pipeline.yml
- add pipeline config for prod
Production apps always have the potential to be foot-guns
> add pipeline config for production

- migrator/dns.py
- tests/unit/test_dns.py
- handle dns timeout errors
- add logging about dns errors
None
> handle dns timeout errors

- docker/Dockerfile.dev
- update PG install commands for new debian version
None
> update for bullseye

- migrator/dns.py
- tests/unit/test_dns.py
- handle all DNS exceptions so we can keep going 
None
> handle all exceptions during DNS resolution

- migrator/__main__.py
- migrator/migration.py
- tests/lib/fake_aws.py
- tests/unit/test_arg_parse.py
- allow forcing migration of single-instances
None
> allow forcing migration of single-instances

- migrator/migration.py
- tests/lib/fake_cloudfront.py
- tests/unit/test_cdn_migration.py
- handle case where boto leaves off items when array is empty
None
> handle case where boto leaves off items when array is empty

- ci/pipeline.yml
- Updated to new CF Resource and harden resources
This hardens our concourse resources
> Updated to new CF Resource and harden resources

- flagger/queries.py
- migrator/db.py
- migrator/models/cdn.py
- migrator/models/common.py
- migrator/models/domain.py
- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- requirements.txt
- tests/lib/database.py
- tests/unit/test_alb_db.py
- tests/unit/test_cdn_db.py
- update dependencies
- sqlalchemy 1.4 -> 2.0 changes
None
> version bumps

- pip-tools/dev-requirements.txt
- requirements.txt
- version bumps again
-
-
Better versions == fewer vulns
> version bumps again

- ci/pipeline.yml
- pip-tools/dev-requirements.txt
- requirements.txt
- Upgrade dependency versions to address security alerts
Upgrading to the latest package versions include the latest security fixes and patches, including remediations for active security alerts
> Upgrade dependency versions

- tests/integration/test_cdn_migration.py
- tests/integration/test_migration.py
- replace http-level mocking with function-level mocks for higher-level functions. This will make it easier to change the API version under the hood, and also makes it a lot easier to focus on any given test's goals and scope. I didn't do this for tests that only interact with v3 of the API, because I'm short on time to do so.
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of …
> refactor: Replace requests_mock with function mocking

- docker/Dockerfile.dev
- docker/docker-compose.yml
- docker/start-servers.sh
- migrator/config.py
- Updated postgres user so now the tests pass
- Also fixed some syntax and formatting
None
> Fix test postgresql server
