cloud-gov/external-domain-broker-migrator

- migrator/db.py
- migrator/models.py
- tests/lib/database.py
- tests/unit/test_cdn_db.py
- Rename shared session to indicate it manages both sessions
- pass cdn_engine around as a parameter
- make declarative base name more obvious
None
> Prep for two connections

- migrator/extensions.py
- migrator/migration.py
- tests/conftest.py
- tests/lib/fake_iam.py
- tests/unit/test_migration.py
- add certificate to external-domain-broker db. fixes #39 
- refactor EdbCdnServiceInstance loading on Migration to be manual rather than automagical
None
> Add certificate to external-domain-broker db

- migrator/config.py
- migrator/extensions.py
- migrator/service_plan.py
- pip-tools/dev-requirements.in
- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- requirements.txt
- tests/conftest.py
- tests/unit/test_config.py
- tests/unit/test_service_plan.py
- Add cf client
- add fixtures for CF client
The testing here is done by mocking the `requests` library. I tried to avoid this, because it feels like it assumes too much knowledge about what cloudfoundry-client is doing, but I also tried mocking that library and things got out of hand quick, and required even more knowledge about the client, so I think this is better? maybe? 
Said differently:
This testing will break very hard if the library stops using `requests` but that is the _de facto_ library in python, and has been for years. The alternative is to mock out the library itself, which takes a ton more fixtures, and will probably break more frequently in smaller ways.
None
> add cf client and fixtures for testing it

- flagger/__main__.py
- flagger/aws.py
- flagger/queries.py
- migrator/config.py
- migrator/models.py
- tests/lib/fake_route53.py
- tests/unit/test_aws.py
- tests/unit/test_cdn_db.py
- tests/unit/test_flagger.py
Addresses #58 
- This script will be able to generate TXT records for domains within our Route53 configuration
- Only operators who have access to our AWS accounts will be able to run it
> Script to generate TXT records for domains that will need to be migrated

- migrator/cf.py
- migrator/migration.py
- tests/unit/test_cf.py
- tests/unit/test_migration.py
This changeset adds support to disable an existing service plan.  When a service plan is created, it is associated to an organization and represented via a unique object, a service plan visibility.  When disabling a plan, you remove this object via its own GUID.
- Adds functionality for disabling a service plan
- Tests for new functionality
- None
> Add support for disabling a service plan

- flagger/aws.py
- migrator/cf.py
- migrator/config.py
- migrator/extensions.py
- migrator/migration.py
- tests/lib/fake_route53.py
- tests/unit/test_cf.py
- tests/unit/test_migration.py
This changeset adds support for instantiating a migrator service in each space found within an org.  This is needed once a customer is ready to perform a migration to the external domain broker.
- Adds ability to retrieve all spaces in an org
- Adds support for instantiating a migrator service in all spaces within an org
- Adds tests for the new functionality
- None; just adds support for creating a new service programmatically
> Add support to instantiate a migrator service in each space of an org

- flagger/__main__.py
- flagger/aws.py
- flagger/queries.py
- add DNS preloading to the flagger script. fixes #77 
I'm not 100% sure I like doing it this way, since it might get kinda funky with the ALB instances. I also considered doing these updates as part of the migrator itself. The upsides there are that it's easier to test and we have more logic available to us. The downsides are that we could end up racking up a bit of route53 upsert API charges (although I don't think it'd be too bad) and that I'd have to rewrite it.
None
> Dns preload

- migrator/cf.py
- don't reference nonexistent vars in logging calls
None
> don't reference nonexistent vars in logging calls

- ci/pipeline.yml
- migrator/config.py
- migrator/extensions.py
- migrator/migration.py
- migrator/models.py
- tests/conftest.py
- tests/lib/fake_iam.py
- tests/unit/test_cdn_migration.py
- tests/unit/test_config.py
- tests/unit/test_domain_migration.py
- add `migration` function for `DomainMigration` fixes #98 
- add active certificate logic to `DomainMigration`
- move `migration` function to `Migration`, wrapping
`DomainMigration::_migration` an `CdnMigration::_migration`
- add govcloud iam config
None
> Add `migration` function for `DomainMigration`

- migrator/config.py
- tests/unit/test_config.py
- make cloudfront_hosted_zone_id available to all configs
None
> make cloudfront_hosted_zone_id available to all configs

- ci/pipeline.yml
- migrator/config.py
- migrator/migration.py
- tests/unit/test_cdn_migration.py
- tests/unit/test_config.py
- tests/unit/test_domain_migration.py
- tests/unit/test_migration.py
- reference plan id. Catalog id is apparently useless 🤷 
- 
- 
None
> use plan id rather than catalog id, since that's what CAPI wants

- migrator/migration.py
- set `external_domain_broker_service_instance` to `None` so `repr` always works. Right now, if we hit an exception before we have an `external_domain_broekr_service_instance`, the exception handler blows up too and we can't see what happened
[Note the any security considerations here, or make note of why there are none]
> set external_domain_broker_service_instance to None so repr always works

- migrator/cf.py
- tests/unit/test_cf.py
catch errors caused by trying to create a service plan visibility that
already exists
don't return the service plan visibility guid, either. We're ignoring
it, and don't have it when we catch a conflict error
- catch errors caused by trying to create a service plan visibility that
already exists
- don't return the service plan visibility guid, either. We're ignoring
it, and don't have it when we catch a conflict error
None
> ignore errors caused by existing visibility

- migrator/config.py
- tests/unit/test_config.py
- sqlalchemy 1.4.x doesn't support postgres:// anymore, so normalize the uris
None
> normalize postgresql uris for sqlalchemy

- docker/Dockerfile.dev
- fix Dockerfile install of PostgreSQL to fix broken CI testing job
None
> fix Dockerfile install of PostgreSQL

- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- requirements.txt
- tests/lib/fake_cf.py
- bump versions
- consistently use http for local testing so requests-mock can consistently capture requests
newer versions have fewer vulns
> fix versions, use consistent testing protocol

- dev
- pip-tools/dev-requirements.txt
- requirements.txt
- Update certifi >= 2024.7.4 to address security alert
- Update urllib 1.26.19 to address security alert
Addresse active Dependabot security alerts
> Address security alerts

- ci/pipeline.yml
- Deprecate use of S3 credentials file in favor of Credhub
Credhub is the authorized secret store for Concourse, so updating the pipeline to use Credhub for variables instead of a file improves security and consistency across our pipelines
> Update pipeline to use credhub vars

- migrator/config.py
- tests/unit/test_config.py
- enforce ssl on database connections
TLS security will now be enforced for database connections, which improves security
> enforce ssl on database connections

- migrator/cf.py
- migrator/migration.py
- migrator/models/common.py
- migrator/models/domain.py
- tests/integration/test_cdn_migration.py
- tests/integration/test_migration.py
- tests/unit/test_cf.py
- tests/unit/test_domain_migration.py
- Upgrade v2/service_plan_visibilities calls to v3/service_plan/:plan/visibility
No direct security considerations here. Removing calls to CAPI v2 will make sure we can keep upgrading CF as needed, which is a security bonus.
> chore: Upgrade service_plan_visibility calls to cf API v3

- migrator/cf.py
- tests/unit/test_cf.py
The process for the migration is roughly:
- Provision a new external-domain service instance with a temporary name
- Once the new domain service is up and running, delete the service instance from the old broker
- Rename the new service instance to have the same name as the service from the old broker
During testing, I noticed that deleting the service instance from the old broker can fail silently. When this error occurs, the next step to rename the new service instance with the name of the old service instance fails, because the old service instance still exists.
This PR updates the migrator to verify deletion of old service instance during migration, which should make it much clearer why the migration has failed.
- For any logging statements, is there any chance that they could be …
> Verify service deletion
